export enum BackgroundEnum {
    Acolyte = "Acolyte",
    Charlatan = "Charlatan",
    Criminal = "Criminal",
    Entertainer = "Entertainer",
    Folk = "Folk",
    Guild = "Guild",
    Hermit = "Hermit",
    Noble = "Noble",
    Outlander = "Outlander",
    Sage = "Sage",
    Sailor = "Sailor",
    Soldier = "Soldier",
    Urchin = "Urchin",
}