export enum ConditionEnum {
    Blinded = "Blinded",
    Charmed = "Charmed",
    Deafened = "Deafened",
    Frightened = "Frightened",
    Grappled = "Grappled",
    Incapacitated = "Incapacitated",
    Invisible = "Invisible",
    Paralyzed = "Paralyzed",
    Petrified = "Petrified",
    Exhaustion1 = "Exhaustion1",
    Exhaustion2 = "Exhaustion2",
    Exhaustion3 = "Exhaustion3",
    Exhaustion4 = "Exhaustion4",
    Exhaustion5 = "Exhaustion5",
    Exhaustion6 = "Exhaustion6",
    Poisoned = "Poisoned",
    Prone = "Prone",
    Restrained = "Restrained",
    Stunned = "Stunned",
    Unconscious = "Unconscious"
}
