export enum LanguageEnum {
    Common = "Common",
    Dwarvish = "Dwarvish",
    Elvish = "Elvish",
    Giant = "Giant",
    Gnomish = "Gnomish",
    Goblin = "Goblin",
    Halfling = "Halfling",
    Orc = "Orc",
    Abyssal = "Abyssal",
    Celestial = "Celestial",
    Draconic = "Draconic",
    DeepSpeech = "DeepSpeech",
    Infernal = "Infernal",
    Primordial = "Primordial",
    Sylvan = "Sylvan",
    Undercommon = "Undercommon",
}
