export enum LevelEnum {
    One = "One",
    Two = "Two",
    Three = "Three",
    Four = "Four",
    Five = "Five",
    Six = "Six",
    Seven = "Seven",
    Eight = "Eight",
    Nine = "Nine",
    Ten = "Ten",
    Eleven = "Eleven",
    Twelve = "Twelve",
    Thirteen = "Thirteen",
    Fourteen = "Fourteen",
    Fifteen = "Fifteen",
    Sixteen = "Sixteen",
    Seventeen = "Seventeen",
    Eighteen = "Eighteen",
    NineTeen = "NineTeen",
    Twenty = "Twenty",
}
