export enum SkillEnum {
    Acrobatics = "Acrobatics",
    AnimalHandling = "AnimalHandling",
    Arcana = "Arcana",
    Athletics = "Athletics",
    Deception = "Deception",
    History = "History",
    Insight = "Insight",
    Intimidation = "Intimidation",
    Investigation = "Investigation",
    Medicine = "Medicine",
    Nature = "Nature",
    Perception = "Perception",
    Performance = "Performance",
    Persuasion = "Persuasion",
    Religion = "Religion",
    SleightOfHand = "SleightOfHand",
    Stealth = "Stealth",
    Survival = "Survival",
}
