export enum ArmorEnum {
    Padded = "Padded",
    Leather = "Leather",
    StuddedLeather = "StuddedLeather",
    Hide = "Hide",
    ChainShirt = "ChainShirt",
    ScaleMail = "ScaleMail",
    Breastplate = "Breastplate",
    HalfPlate = "HalfPlate",
    RingMail = "RingMail",
    ChainMail = "ChainMail",
    Splint = "Splint",
    Plate = "Plate",
    Shield = "Shield",
};
